### ISSUE TITLE
Can we get a license for this?

### ISSUE THREAD

**Issue by NCommander** [vsimon/webrtcbuilds-builder#3]
First off, I'd like to thank you for your work on actually making webRTC native be usable for anyone who isn't Google.

I have a small request. Would it be put the builder stuff under an actual license so it can be redistributed freely? (I'd personally like to see it licensed under three-clause BSD license like libwebrtc itself)

**Comment by vsimon** [comment]
Thanks for the suggestion. Yes, of course. 59f0416cf99619f5052fe390ef5d5ef8845e31d5
